import "./globals.css";

export const metadata = {
  title: "Nextjs ProjectOne",
  description: "Generated by create next app",
};

export default function RootLayout({children}){
  return(
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
